// _fwbuild/react-todo/components/TaskForm.jsx
      import { useCallback, useId, useRef, useState } from 'react';
      import Icon from './Icons.jsx';
      import { MAX_NOTES, MAX_TITLE, PRIORITIES, TAG_LIBRARY } from '../utils/todoStore.js';
      import { todayInputValue } from '../utils/date.js';

      const EMPTY = { title: '', notes: '', priority: 'medium', due: '', tags: '' };

      /**
       * The add/edit form.
       *
       * Doubles as the inline editor: when `editing` is passed it is pre-filled and
       * submits an update instead of an insert. Submit happens on Enter from the title
       * field (or anywhere in the form) while Shift+Enter stays available in notes.
       */
      export default function TaskForm({ onCreate, onUpdate, editing, onCancelEdit, defaultPriority = 'medium' }) {
        const [draft, setDraft] = useState(EMPTY);
        const [error, setError] = useState('');
        const [touched, setTouched] = useState(false);
        const titleRef = useRef(null);
        const formId = useId();

        const isEditing = Boolean(editing);

        // When the parent promotes a row into edit mode, adopt that row's values.
        const values = isEditing
          ? {
              title: editing.title,
              notes: editing.notes,
              priority: editing.priority,
              due: editing.due,
              tags: editing.tags.join(', '),
            }
          : { ...EMPTY, priority: defaultPriority };

        const set = useCallback((key) => (event) => {
          const { value } = event.target;
          setDraft((current) => ({ ...current, [key]: value }));
          if (key === 'title') setError('');
        }, []);

        const remaining = MAX_TITLE - draft.title.length;

        const handleSubmit = (event) => {
          event.preventDefault();
          const title = draft.title.trim();

          if (!title) {
            setError('Give the task a name before saving.');
            setTouched(true);
            if (titleRef.current) titleRef.current.focus();
            return;
          }
          if (title.length < 3) {
            setError('Three characters or more, please.');
            setTouched(true);
            return;
          }

          setTouched(false);
          setError('');

          if (isEditing) {
            onUpdate(editing.id, {
              title,
              notes: draft.notes.trim(),
              priority: draft.priority,
              due: draft.due,
              tags: draft.tags,
            });
            onCancelEdit();
          } else {
            onCreate({
              title,
              notes: draft.notes.trim(),
              priority: draft.priority,
              due: draft.due,
              tags: draft.tags,
            });
            setDraft({ ...EMPTY, priority: defaultPriority });
          }
        };

        const handleCancel = () => {
          setDraft(EMPTY);
          setError('');
          setTouched(false);
          onCancelEdit();
        };

        return (
          <form className="task-form" onSubmit={handleSubmit} noValidate>
            <div className="task-form__head">
              <h2 className="task-form__title">
                <Icon name={isEditing ? 'pencil' : 'plus'} size={16} />
                {isEditing ? 'Edit task' : 'New task'}
              </h2>
              <button
                type="button"
                className="ghost-button"
                onClick={() => setDraft((current) => ({ ...current, due: current.due === todayInputValue() ? '' : todayInputValue() }))}
                aria-label="Toggle due date of today"
              >
                <Icon name="calendar" size={15} />
                {draft.due === todayInputValue() ? 'Today' : 'Due today'}
              </button>
            </div>

            <label className="field">
              <span className="field__label">Task name</span>
              <input
                ref={titleRef}
                id={formId + '-title'}
                className="input"
                type="text"
                value={draft.title}
                onChange={set('title')}
                onBlur={() => setTouched(true)}
                placeholder="Ship the pricing page copy review"
                maxLength={MAX_TITLE}
                autoComplete="off"
                aria-describedby={formId + '-count' + (error ? ' ' + formId + '-error' : '')}
                aria-invalid={Boolean(error) || undefined}
              />
              <span className="field__meta">
                <span
                  id={formId + '-count'}
                  className={'counter' + (remaining <= 10 ? ' counter--warn' : '')}
                  aria-live="polite"
                >
                  {remaining} left
                </span>
              </span>
            </label>

            <label className="field">
              <span className="field__label">Notes</span>
              <textarea
                id={formId + '-notes'}
                className="input input--area"
                rows={2}
                value={draft.notes}
                onChange={set('notes')}
                placeholder="Context, links, acceptance criteria"
                maxLength={MAX_NOTES}
              />
            </label>

            <div className="task-form__row">
              <label className="field field--compact">
                <span className="field__label">Priority</span>
                <select id={formId + '-priority'} className="input input--select" value={draft.priority} onChange={set('priority')}>
                  {PRIORITIES.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.label}
                    </option>
                  ))}
                </select>
              </label>

              <label className="field field--compact">
                <span className="field__label">Due</span>
                <input
                  id={formId + '-due'}
                  className="input input--date"
                  type="date"
                  value={draft.due}
                  onChange={set('due')}
                />
              </label>
            </div>

            <fieldset className="field field--tags">
              <legend className="field__label">Tags</legend>
              <div className="chip-row chip-row--pick">
                {TAG_LIBRARY.map((tag) => {
                  const active = draft.tags.split(',').some((part) => part.trim() === tag);
                  return (
                    <button
                      key={tag}
                      type="button"
                      className={'chip chip--button' + (active ? ' chip--on' : '')}
                      aria-pressed={active}
                      onClick={() => {
                        const parts = draft.tags.split(',').map((s) => s.trim()).filter(Boolean);
                        const next = parts.indexOf(tag) === -1
                          ? parts.concat(tag)
                          : parts.filter((p) => p !== tag);
                        setDraft((current) => ({ ...current, tags: next.join(', ') }));
                      }}
                    >
                      {tag}
                    </button>
                  );
                })}
              </div>
              <input
                id={formId + '-tags'}
                className="input input--tags"
                type="text"
                value={draft.tags}
                onChange={set('tags')}
                placeholder="custom tags, comma separated"
                aria-label="Custom tags, comma separated"
              />
            </fieldset>

            {touched && error ? (
              <p className="form-error" id={formId + '-error'} role="alert">
                <Icon name="close" size={14} />
                {error}
              </p>
            ) : null}

            <div className="task-form__actions">
              <button type="submit" className="button button--primary">
                <Icon name={isEditing ? 'check' : 'plus'} size={16} />
                {isEditing ? 'Save changes' : 'Add task'}
              </button>
              {isEditing ? (
                <button type="button" className="button button--quiet" onClick={handleCancel}>
                  Cancel
                </button>
              ) : null}
              <p className="form-hint">Press Enter to save. Notes accept up to {MAX_NOTES} characters.</p>
            </div>
          </form>
        );
      }

// _fwbuild/vue-tasks/components/TaskForm.vue
      <script setup>
      import { computed, reactive, ref, watch } from 'vue';
      import { MAX_TITLE, PRIORITIES } from '../utils/labels.js';
      import { today } from '../data/seed.js';

      /**
       * The add form.
       *
       * `v-model` on every field binds straight into one `reactive` draft, so there is
       * no per-field `ref` plumbing and the reset is a single object replacement.
       */
      const props = defineProps({
        /** Task being edited, or null when adding. */
        editing: { type: Object, default: null },
      });

      const emit = defineEmits(['create', 'update', 'cancel-edit']);

      const blank = () => ({
        title: '',
        note: '',
        priority: 'medium',
        due: '',
      });

      const draft = reactive(blank());
      const error = ref('');
      const touched = ref(false);

      const isEditing = computed(() => Boolean(props.editing));

      /** The live model is the draft while adding, and the task being edited. */
      const remaining = computed(() => MAX_TITLE - draft.title.length);
      const isWarn = computed(() => remaining.value <= 10);

      /** Fill the form from the task being edited, without mutating the prop. */
      const hydrate = (task) => {
        Object.assign(draft, {
          title: task.title,
          note: task.note,
          priority: task.priority,
          due: task.due,
        });
      };

      const hydrateFrom = (task) => {
        if (task) hydrate(task);
        else Object.assign(draft, blank());
      };

      /**
       * Which task is being edited, or the string 'new' when the form is adding.
       * Watching this is enough to know when to re-hydrate the draft, and it avoids
       * depending on the identity of the prop object.
       */
      const mode = computed(() => (props.editing ? props.editing.id : 'new'));

      watch(mode, (next, previous) => {
        if (next === previous) return;
        hydrateFrom(next === 'new' ? null : props.editing);
        error.value = '';
        touched.value = false;
      });

      // Covers the parent mounting with a row already in edit mode. Without this the
      // draft would stay blank until the mode actually changed.
      if (props.editing) hydrate(props.editing);

      const onTitle = () => {
        error.value = '';
      };

      const onSubmit = () => {
        const title = draft.title.trim();

        if (!title) {
          error.value = 'Give the task a name first.';
          touched.value = true;
          return;
        }
        if (title.length < 3) {
          error.value = 'Three characters or more, please.';
          touched.value = true;
          return;
        }

        touched.value = false;
        error.value = '';

        const payload = {
          title,
          note: draft.note.trim(),
          priority: draft.priority,
          due: draft.due,
          tags: [],
        };

        if (isEditing.value) emit('update', props.editing.id, payload);
        else emit('create', payload);

        Object.assign(draft, blank());
      };

      const toggleQuickDue = () => {
        const t = today();
        draft.due = draft.due === t ? '' : t;
      };

      const cancel = () => {
        Object.assign(draft, blank());
        error.value = '';
        touched.value = false;
        emit('cancel-edit');
      };
      </script>

      <template>
        <form class="form" novalidate @submit.prevent="onSubmit">
          <header class="form__head">
            <h2 class="form__title">
              <svg v-if="isEditing" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
                <path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20ZM13.5 6.5l3 3" />
              </svg>
              <svg v-else width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-width="1.9" stroke-linecap="round" aria-hidden="true" focusable="false">
                <path d="M12 5v14M5 12h14" />
              </svg>
              {{ isEditing ? 'Edit task' : 'New task' }}
            </h2>

            <button type="button" class="ghost ghost--tiny" @click="toggleQuickDue">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"
                stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
                <path d="M4 7h16v14H4zM4 11h16M8 4v4M16 4v4" />
              </svg>
              {{ draft.due === today() ? 'Due today' : 'Today' }}
            </button>
          </header>

          <div class="field">
            <label class="field__label" for="new-title">Task name</label>
            <input
              id="new-title"
              v-model="draft.title"
              class="input"
              type="text"
              :maxlength="MAX_TITLE"
              placeholder="Collect the Q2 audit evidence"
              autocomplete="off"
              :aria-invalid="Boolean(touched && error) || undefined"
              aria-describedby="title-count"
              @blur="touched = true"
              @input="onTitle"
            />
            <div class="field__foot">
              <span id="title-count" class="counter" :class="{ 'counter--warn': isWarn }" aria-live="polite">
                {{ remaining }} left
              </span>
            </div>
          </div>

          <div class="field">
            <label class="field__label" for="new-note">Note</label>
            <textarea
              id="new-note"
              v-model="draft.note"
              class="input input--area"
              rows="2"
              maxlength="240"
              placeholder="Context or acceptance criteria"
            />
          </div>

          <div class="form__row">
            <div class="field field--compact">
              <label class="field__label" for="new-priority">Priority</label>
              <select id="new-priority" v-model="draft.priority" class="input input--select">
                <option v-for="option in PRIORITIES" :key="option.id" :value="option.id">{{ option.label }}</option>
              </select>
            </div>

            <div class="field field--compact">
              <label class="field__label" for="new-due">Due date</label>
              <input id="new-due" v-model="draft.due" class="input input--date" type="date" />
            </div>
          </div>

          <p v-if="touched && error" class="form__error" role="alert">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
              stroke-linecap="round" aria-hidden="true" focusable="false">
              <path d="M6 6l12 12M18 6 6 18" />
            </svg>
            {{ error }}
          </p>

          <div class="form__actions">
            <button type="submit" class="button button--primary">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
                <path :d="isEditing ? 'm20 6-11 11-5-5' : 'M12 5v14M5 12h14'" />
              </svg>
              {{ isEditing ? 'Save changes' : 'Add task' }}
            </button>

            <button v-if="isEditing" type="button" class="button button--quiet" @click="cancel">Cancel</button>

            <p class="form__hint">Enter saves the task.</p>
          </div>
        </form>
      </template>
